OrdererOrgs:
  - Name: Orderer
    CaFile: static\\ca.yaml
    Domain: example.com
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: Org1
    CaFile: static\\ca.yaml
    Domain: org1.example.com
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: Org2
    CaFile: static\\ca.yaml
    Domain: org2.example.com
    Template:
      Count: 2
    Users:
      Count: 1

Output: D:/crypto-config

Subject:
  Country: CN
  Province: BeiJing
  Locality: BeiJing
  Organization: Hynet
  OrganizationalUnit: 
